#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"

const modelsUrl = process.env.IDEASPACE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

type Target =
  | "bun-linux-arm64"
  | "bun-linux-x64"
  | "bun-linux-x64-baseline"
  | "bun-linux-arm64-musl"
  | "bun-linux-x64-musl"
  | "bun-linux-x64-baseline-musl"
  | "bun-darwin-arm64"
  | "bun-darwin-x64"
  | "bun-darwin-x64-baseline"
  | "bun-windows-x64"
  | "bun-windows-x64-baseline"

const allTargets = [
  {
    os: "linux",
    arch: "arm64",
    target: "bun-linux-arm64",
  },
  {
    os: "linux",
    arch: "x64",
    target: "bun-linux-x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
    target: "bun-linux-x64-baseline",
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
    target: "bun-linux-arm64-musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    target: "bun-linux-x64-musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
    target: "bun-linux-x64-baseline-musl",
  },
  {
    os: "darwin",
    arch: "arm64",
    target: "bun-darwin-arm64",
  },
  {
    os: "darwin",
    arch: "x64",
    target: "bun-darwin-x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
    target: "bun-darwin-x64-baseline",
  },
  {
    os: "win32",
    arch: "x64",
    target: "bun-windows-x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
    target: "bun-windows-x64-baseline",
  },
] satisfies ReadonlyArray<{
  os: NodeJS.Platform
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
  target: Target
}>

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if ("avx2" in item && item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if ("abi" in item && item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    "avx2" in item && item.avx2 === false ? "baseline" : undefined,
    "abi" in item && item.abi !== undefined ? item.abi : undefined,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: item.target,
      outfile: `dist/${name}/bin/ideaspace`,
      execArgv: [`--user-agent=ideaspace/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      IDEASPACE_VERSION: `'${Script.version}'`,
      IDEASPACE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      IDEASPACE_WORKER_PATH: workerPath,
      IDEASPACE_CHANNEL: `'${Script.channel}'`,
      IDEASPACE_LIBC: item.os === "linux" ? `'${("abi" in item && item.abi) || "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
